spring:
  datasource:
    url: ${DB_URL}?rewriteBatchedStatements=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        order_updates: true
        jdbc:
          batch_size: 100
server:
  port: 8080