spring:
  application:
    name: TravelMate
  profiles:
    active: local
  jackson:
    deserialization:
      UNWRAP_ROOT_VALUE: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    servlet:
      multipart:
        enabled: true
        max-file-size: 50MB
        max-request-size: 50MB

tour-api:
  korean-info:
    base-url: ${TOUR_API_KOR_INFO_BASE_URL}
    service-key: ${TOUR_API_KOR_INFO_SERVICE_KEY}
  english-info:
    base-url: ${TOUR_API_ENG_INFO_BASE_URL}
    service-key: ${TOUR_API_ENG_INFO_SERVICE_KEY}
  photo-gallery:
    base-url: ${TOUR_API_PHOTO_GALLERY_BASE_URL}
    service-key: ${TOUR_API_PHOTO_GALLERY_SERVICE_KEY}